// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7nAniQNk4_AWyCu6HiOO4kMcaBISBP5U',
    appId: '1:1002601441010:web:1286b2b6038e798bbc926b',
    messagingSenderId: '1002601441010',
    projectId: 'ugo-user-8ff52',
    authDomain: 'ugo-user-8ff52.firebaseapp.com',
    storageBucket: 'ugo-user-8ff52.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA29RG-kmbZmXU6BxF2Uo2qqR3_Jr84ltU',
    appId: '1:1002601441010:android:764afa4a462d3c3ebc926b',
    messagingSenderId: '1002601441010',
    projectId: 'ugo-user-8ff52',
    storageBucket: 'ugo-user-8ff52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvO0YV3ejXEiTcy0dhppGzXp_8wRObF18',
    appId: '1:1002601441010:ios:e094a36041a8ab6cbc926b',
    messagingSenderId: '1002601441010',
    projectId: 'ugo-user-8ff52',
    storageBucket: 'ugo-user-8ff52.firebasestorage.app',
    iosBundleId: 'com.ugocabs.user',
  );

}